"""PULSE loss map — where the model loses money, sliced by decision state.

    .venv/bin/python analysis/pulse_loss_map.py [--tape CSV] [--ledger CSV]
    .venv/bin/python analysis/pulse_loss_map.py --selftest

Reads the exported decision tape (pin: ``20260901T195202Z``), reconstructs
the entry-level round-trip ledger exactly per ``core/pulse/live_report.py``'s
conventions, and prints a markdown loss map: per-$ outcomes cut by market
type, estimator version, the depth axis (price band), game state, spread and
claimed edge. Written to the 2026-09-01 wave standard
(``analysis/WAVE_STANDARD.md``).

EVERYTHING HERE IS DESCRIPTIVE AND IN-SAMPLE — hypothesis-generating, never
gating. Standing caveats on every cell:

1. **Fill-rule optimism** (docs/math/pulse-live.md): a shadow fill happens
   when a newer mid crosses the resting price. Losses are trustworthy;
   profits are upper bounds — doubled on round trips (two optimistic fills).
   A pessimistic arm re-scores fills with the measured in-game concession
   (4.70¢ per filled quote, E[−dmid | fill], docs/findings.md C13 —
   measured on the QUOTE study's 30s windows; the regime mismatch with
   PULSE's resting limits is stated, not hidden).
2. **Clusters are games, not rows** (docs/math/clustered-errors.md). Every
   interval below is game-clustered via the one blessed implementation.
3. **Multiplicity**: the script counts every interval it computes and prints
   the total. At 95%, one in twenty is expected significant by chance.

Population note (the 2026-08-23 ruling in docs/math/pulse-live.md): rows with
``capped_stake_usd = 0`` are cap-blocked intents — annotations, not trades.
They belong only to the FULL-INTENT population, which is where nearly all of
this tape lives (the shadow engine annotates instead of blocking). The
live-faithful subset is reported separately, unsliced — far too small to
cut. Dollar sums over full-intent rows are SHADOW dollars at the model's
desired size, never money live would have committed.

Scoring policy (ONE definition, labelled): maker fee Θ=0 on both legs
(docs/math/fees-and-spread.md — resting limits, no taker path), so gross =
net here.

* round trip  — per-$ = capture / cost, capture in the position's direction
* ride        — per-$ = returned / staked − 1, money at price (C11/V14)
* pooled      — each filled entry contributes its one realized per-$ outcome
  (trip capture if its exit filled, ride ROI otherwise). Pooling legs is a
  map convenience; the legs are also shown split, because their evidence
  quality differs (the trip leg is optimistic twice).

The substrate is Quant A's round-trip ledger
(``backups/exports/roundtrip_ledger_20260901T195202Z.csv``, regenerated by
``analysis/roundtrip_ledger.py`` — wave standard rule 4: one P&L definition,
mutation-tested, venue-reconciled). This script reconciles its own
tape reconstruction against A's ledger and reports every divergence; when the
ledger file is absent it falls back to the reconstruction so the map stays
reproducible from the pinned tape alone. A's ``lineage_source =
'reconstructed'`` rows (17 early-era orphan exits re-linked by A's stated
rule) are CARRIED, shifting those entries from ride to trip relative to the
raw reconstruction; the reconciliation prints the count.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
import pandas as pd

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from core.quote.adverse_selection import clustered_mean  # noqa: E402
from core.pulse.live_report import (  # noqa: E402
    round_trip_capture,
    settlement_score,
)

DEFAULT_TAPE = REPO / "backups/exports/pulse_decisions_full_20260901T195202Z.csv"
DEFAULT_LEDGER = REPO / "backups/exports/roundtrip_ledger_20260901T195202Z.csv"

#: Measured in-game fill concession, E[−dmid | fill] (docs/findings.md C13:
#: 4.70¢ [4.41, 5.00], 1.9M windows / 13 games). Applied per optimistic fill
#: in the pessimistic arm: twice on a trip, once on a ride's entry.
CONCESSION = 0.047

#: (version, strategy) cells eligible for state cuts. Declared as a rule, not
#: a hand-picked list: cells below these floors produce intervals that are
#: pure noise and would only inflate the comparison count.
CUT_MIN_FILLS = 150
CUT_MIN_GAMES = 8

#: Fixed bucket edges, declared before the first cut executed. The cost
#: (price-band) edges are the venue depth-measurement bands (docs/findings.md
#: V1: ~$5 at the touch under 20¢, ~$24 at 20–35¢, ~$118 at 35–65¢), because
#: the wave's priority question is whether decisions land where size exists.
BUCKETS = {
    "minutes_left": [0, 5, 10, 20, 30, 40.01],
    "abs_margin": [0, 3, 6, 10, 99],
    "edge_net": [0.03, 0.06, 0.10, 0.15, 0.25, 1.0],
    "cost": [0, 0.20, 0.35, 0.65, 1.0],
    "spread_px": [0, 0.02, 0.05, 0.10, 0.1501],
}
DEPTH_LABELS = ["<20¢ (~$5 depth)", "20–35¢ (~$24)", "35–65¢ (~$118)",
                ">65¢"]

#: The v3 deploy instant (docs/math/pulse-live.md): v1 rows AFTER this are
#: stale-clock fallback ticks, a selected population — any v1 pattern must
#: survive this split before it means anything.
V3_DEPLOY = "2026-08-23 19:30"

COMPARISONS = {"n": 0}  # global interval counter, printed at the end

CAPITAL_LINE = ("No in-sample result justifies capital. "
                "The forward test is the evidence.")


def build_ledger(tape: pd.DataFrame) -> pd.DataFrame:
    """Entry-level ledger from the raw tape: one row per FILLED entry, joined
    to its first filled exit, with outcome and decision state."""
    ent = tape[(tape.action == "enter") & tape.filled_at.notna()].copy()
    exits = tape[(tape.action == "exit") & tape.filled_at.notna()].copy()
    orphans = int(tape[(tape.action == "exit")].entry_id.isna().sum())
    if orphans:
        print(f"<!-- data note: {orphans} exit rows carry no entry_id; "
              f"ignored -->")
    exits = (exits.sort_values("filled_at")
                  .drop_duplicates("entry_id", keep="first"))
    x = exits[["entry_id", "limit_price", "filled_at", "reason"]].rename(
        columns={"limit_price": "exit_price", "filled_at": "exit_filled_at",
                 "reason": "exit_reason"})
    m = ent.merge(x, left_on="id", right_on="entry_id", how="left")

    m["is_trip"] = m.exit_filled_at.notna()
    m["cost"] = np.where(m.side == "yes", m.limit_price, 1 - m.limit_price)
    m["spread_px"] = m.market_ask - m.market_bid
    m["abs_margin"] = m.margin.abs()

    rets, legs, cf, pess = [], [], [], []
    for r in m.itertuples():
        staked, returned = settlement_score(
            side=r.side, entry_price=float(r.limit_price),
            settlement=int(r.settlement))
        ride_ret = returned / staked - 1.0
        cf.append(ride_ret)  # counterfactual: ridden to settlement
        if r.is_trip:
            capture = round_trip_capture(
                side=r.side, entry_price=float(r.limit_price),
                exit_price=float(r.exit_price))
            rets.append(capture / r.cost)
            pess.append((capture - 2 * CONCESSION) / r.cost)
            legs.append("trip")
        else:
            rets.append(ride_ret)
            pess.append(returned / (staked + CONCESSION) - 1.0)
            legs.append("ride")
    m["ret"] = rets            # realized per-$ outcome (the engine's choice)
    m["ret_pess"] = pess       # measured-concession arm (regime caveat above)
    m["leg"] = legs
    m["ret_if_ridden"] = cf    # counterfactual hold-to-settlement per-$

    m["live_faithful"] = m.capped_stake_usd.isna() | (m.capped_stake_usd > 0)
    m["pnl_shadow_usd"] = m.ret * m.cost * m.contracts
    return m


def ledger_from_a(path: Path) -> pd.DataFrame:
    """Adapt Quant A's ledger (the wave's substrate) to this script's frame.
    Scored rows only: entry filled, outcome exit_fill (trip) or settlement
    (ride). Per-$ columns are A's own (one labelled P&L definition)."""
    a = pd.read_csv(path)
    m = a[a.entry_filled & a.outcome.isin(["exit_fill", "settlement"])].copy()
    m["leg"] = np.where(m.outcome == "exit_fill", "trip", "ride")
    m["ret"] = m.pnl_per_dollar
    m["ret_pess"] = m.pnl_per_dollar_pess
    m["cost"] = m.entry_cost_per_contract
    m["spread_px"] = m.market_ask - m.market_bid
    m["abs_margin"] = m.margin.abs()
    m["live_faithful"] = ~m.live_blocked
    m["pnl_shadow_usd"] = m.pnl_usd
    m["ret_if_ridden"] = [
        (lambda sr: sr[1] / sr[0] - 1.0)(settlement_score(
            side=r.side, entry_price=float(r.entry_limit_price),
            settlement=int(r.settlement)))
        for r in m.itertuples()
    ]
    n_rec = int((m.lineage_source == "reconstructed").sum())
    print(f"<!-- ledger: {len(m)} scored rows from A "
          f"({(m.leg == 'trip').sum()} trips / {(m.leg == 'ride').sum()} "
          f"rides); {n_rec} lineage_source=reconstructed rows carried "
          f"(rides in the raw reconstruction) -->")
    return m


def reconcile(mine: pd.DataFrame, a: pd.DataFrame) -> None:
    """Print divergences between the tape reconstruction and A's ledger."""
    j = mine[["id", "ret", "leg"]].merge(
        a[["entry_decision_id", "ret", "leg"]],
        left_on="id", right_on="entry_decision_id",
        suffixes=("_mine", "_a"))
    leg_diff = int((j.leg_mine != j.leg_a).sum())
    same_leg = j[j.leg_mine == j.leg_a]
    max_dret = float((same_leg.ret_mine - same_leg.ret_a).abs().max())
    print(f"<!-- reconciliation vs tape reconstruction: rows "
          f"{len(mine)} (mine) / {len(a)} (A), joined {len(j)}, leg "
          f"mismatches {leg_diff} (expected: A's re-linked orphans), max "
          f"|Δper-$| on same-leg rows {max_dret:.6f} -->")


def cell_stats(g: pd.DataFrame, label: str, *, col: str = "ret",
               count: bool = True) -> str:
    """One markdown table row: n, games, shadow $, clustered per-$ CI."""
    by_game: dict[str, list[float]] = {}
    for slug, vals in g.groupby("event_slug")[col]:
        by_game[slug] = list(vals)
    cm = clustered_mean(by_game)
    n, games = len(g), g.event_slug.nunique()
    usd = g.pnl_shadow_usd.sum()
    trips = int((g.leg == "trip").sum())
    if cm is None:
        return (f"| {label} | {n} | {games} | {trips} | {usd:+,.0f} | "
                f"— (needs ≥2 games) |")
    if count:
        COMPARISONS["n"] += 1
    flag = " ◄" if cm.hi < 0 else (" ▷" if cm.lo > 0 else "")
    return (f"| {label} | {n} | {games} | {trips} | {usd:+,.0f} | "
            f"{cm.mean * 100:+.1f}¢ [{cm.lo * 100:+.1f}, "
            f"{cm.hi * 100:+.1f}]{flag} |")


HEADER = ("| cut | n | games | trips | shadow $ | per-$ clustered "
          "[95% CI] |\n|---|---|---|---|---|---|")


def depth_band(g: pd.DataFrame) -> pd.Series:
    return pd.cut(g["cost"], bins=BUCKETS["cost"], include_lowest=True,
                  labels=DEPTH_LABELS)


def _bin(g: pd.DataFrame, col: str) -> pd.Series:
    edges = BUCKETS[col]
    labels = [f"({lo:g}, {hi:g}]" for lo, hi in zip(edges, edges[1:])]
    return pd.cut(g[col], bins=edges, include_lowest=True, labels=labels)


def state_cuts(g: pd.DataFrame, cell_name: str) -> list[str]:
    out = [f"\n### State cuts — {cell_name}\n", HEADER]
    for col in ["period", "side", "leg"]:
        for val, sub in g.groupby(col, observed=True):
            out.append(cell_stats(sub, f"{col}={val}"))
    for col in ["minutes_left", "abs_margin", "edge_net", "cost",
                "spread_px"]:
        for val, sub in g.groupby(_bin(g, col), observed=True):
            if len(sub) == 0:
                continue
            out.append(cell_stats(sub, f"{col} {val}"))
    trips = g[g.leg == "trip"]
    for val, sub in trips.groupby("exit_reason"):
        out.append(cell_stats(sub, f"exit={val} (trips)"))
    return out


def run_map(m: pd.DataFrame, tape_name: str) -> None:
    print("# PULSE loss map — descriptive, in-sample, full-intent tape")
    print()
    print(f"Tape: `{tape_name}` · filled entries {len(m):,} · games "
          f"{m.event_slug.nunique()} · trips {(m.leg == 'trip').sum():,} · "
          f"rides {(m.leg == 'ride').sum():,}")
    print()
    print("**Read this first:** shadow fills are optimistic (losses real, "
          "profits upper bounds, doubly so on trips); every interval is "
          "game-clustered; the comparison count at the bottom is the "
          "multiplicity bill. Units: per-$ outcomes in cents per dollar "
          "staked; shadow $ at model-desired size. Policy: maker Θ=0, "
          "gross = net. ◄ = CI fully below zero, ▷ = CI fully above zero "
          "(an upper bound, not a finding).")

    print("\n## 1. The map — estimator version × market type\n")
    print(HEADER)
    for (v, s), g in m.groupby(["estimates_version", "strategy"]):
        print(cell_stats(g, f"{v} {s}"))
    print(cell_stats(m, "ALL (mixed models — counts context only)",
                     count=False))

    print("\n## 2. The depth axis — do decisions land where size exists?\n")
    print("Composition first (counts, before any ratio): filled entries "
          "per price band, by version × market type. Bands are the venue "
          "depth measurements (V1).\n")
    comp = (m.assign(band=depth_band(m))
             .groupby(["estimates_version", "strategy", "band"],
                      observed=True).size().unstack(fill_value=0))
    bands = list(comp.columns)
    print("| cell | " + " | ".join(bands) + " |")
    print("|---" * (len(bands) + 1) + "|")
    for (v, s), row in comp.iterrows():
        print(f"| {v} {s} | " + " | ".join(str(row[b]) for b in bands) + " |")
    print()
    print("Per-$ outcomes by band (all versions/types — mixed-model row "
          "for orientation, then the big cells):\n")
    print(HEADER)
    for band, sub in m.groupby(depth_band(m), observed=True):
        print(cell_stats(sub, f"ALL — {band}", count=False))
    for (v, s), g in m.groupby(["estimates_version", "strategy"]):
        if len(g) < CUT_MIN_FILLS:
            continue
        for band, sub in g.groupby(depth_band(g), observed=True):
            print(cell_stats(sub, f"{v} {s} — {band}"))

    print("\n## 3. Trip vs ride, exit counterfactual, pessimistic arm\n")
    print(HEADER)
    for (v, s), g in m.groupby(["estimates_version", "strategy"]):
        for leg, sub in g.groupby("leg"):
            print(cell_stats(sub, f"{v} {s} — {leg}"))
    print()
    print("Counterfactual (every filled entry ridden to settlement, same "
          "fills — isolates the exit engine's contribution):\n")
    print(HEADER)
    for (v, s), g in m.groupby(["estimates_version", "strategy"]):
        print(cell_stats(g, f"{v} {s} — if ridden", col="ret_if_ridden"))
    print()
    print(f"Pessimistic arm (measured in-game concession "
          f"{CONCESSION * 100:.1f}¢ per fill — QUOTE-study regime, mismatch "
          f"stated in the header):\n")
    print(HEADER)
    for (v, s), g in m.groupby(["estimates_version", "strategy"]):
        print(cell_stats(g, f"{v} {s} — pessimistic", col="ret_pess"))

    print("\n### 3b. Where do rides happen? (composition — counts, "
          "no intervals)\n")
    print("A ride is a fill whose exit never filled. If rides concentrate "
          "late / in decided games, the ride losses are the bookless-endgame "
          "mechanism, not an independent finding.\n")
    m2 = m.assign(mlb=_bin(m, "minutes_left"), amb=_bin(m, "abs_margin"))
    for dim, col in [("minutes_left", "mlb"), ("abs_margin", "amb"),
                     ("period", "period")]:
        rows = []
        for val, sub in m2.groupby(col, observed=True):
            rides = int((sub.leg == "ride").sum())
            rows.append(f"| {dim} {val} | {len(sub)} | {rides} | "
                        f"{rides / len(sub) * 100:.1f}% |")
        print(f"| cut | fills | rides | ride share |\n|---|---|---|---|")
        print("\n".join(rows))
        print()

    print("\n### 3c. Portfolio counterfactual — drop the ride-tail states\n")
    print("Same fills, entries decided in Q4 or at |margin| ≥ 10 removed "
          "(the two states where ride share doubles). In-sample by "
          "construction — the filter was chosen after seeing 3b — so this "
          "is the candidate's effect size, not evidence.\n")
    print(HEADER)
    tail = (m.period == "Q4") | (m.abs_margin >= 10)
    print(cell_stats(m[~tail], "kept: not Q4, |margin| < 10"))
    print(cell_stats(m[tail], "dropped: Q4 or |margin| >= 10"))

    print("\n### 3d. Robustness: the v1 era split\n")
    print("v1 rows before the v3 deploy are the original estimator's era; "
          "v1 rows AFTER it are stale-clock fallback ticks — a selected "
          "population (the venue clock was missing or stale). Any v1 cell "
          "read as a candidate must survive this split.\n")
    print(HEADER)
    v1 = m[m.estimates_version == "v1"].copy()
    era = np.where(v1.decided_at < V3_DEPLOY, "era (pre-v3 deploy)",
                   "stale-clock fallback (post)")
    for (e, s), g in v1.groupby([era, "strategy"]):
        print(cell_stats(g, f"v1 {s} — {e}"))

    big = [(v, s) for (v, s), g in m.groupby(["estimates_version",
                                              "strategy"])
           if len(g) >= CUT_MIN_FILLS
           and g.event_slug.nunique() >= CUT_MIN_GAMES]
    print(f"\n## 4. State cuts within big cells "
          f"(≥{CUT_MIN_FILLS} fills, ≥{CUT_MIN_GAMES} games: "
          f"{', '.join(f'{v} {s}' for v, s in big)})")
    print("\nNote on the exit-reason rows: exit reason is not knowable at "
          "entry — a profit-target exit is +5¢ capture BY CONSTRUCTION and "
          "a stop realizes a loss by construction. Those rows describe the "
          "composition of outcomes, not entry-time structure.")
    for v, s in big:
        g = m[(m.estimates_version == v) & (m.strategy == s)]
        print("\n".join(state_cuts(g, f"{v} {s}")))

    lf = m[m.live_faithful]
    print("\n## 5. Live-faithful subset (registered population — "
          "unsliced, far below floor)\n")
    print(HEADER)
    print(cell_stats(lf, "live-faithful, all", count=False))
    print(f"\nFloors are 100 fills / 10 games "
          f"(currently {len(lf)} / {lf.event_slug.nunique()}); the "
          f"registered series stays NO DATA and this map does not touch it.")

    print(f"\n---\n**Comparisons computed: {COMPARISONS['n']} "
          f"game-clustered intervals.** At 95%, expect "
          f"~{max(1, round(COMPARISONS['n'] / 20))} spuriously "
          f"'significant' cells from chance alone. Ranking of any candidate "
          f"is mechanism plausibility + effect size + robustness across "
          f"slices — never p-value.")
    print(f"\n**{CAPITAL_LINE}**")


# --------------------------------------------------------------------------
# Mutation self-test (wave standard rule 4): the pipeline must read ~zero on
# a synthetic null and recover a synthetic injected effect.
# --------------------------------------------------------------------------

def _synthetic_tape(rng: np.random.Generator, *, inject: float,
                    games: int = 40, per_game: int = 30) -> pd.DataFrame:
    rows = []
    rid = 0
    for gi in range(games):
        for _ in range(per_game):
            rid += 1
            p = rng.uniform(0.10, 0.90)
            side = "yes" if rng.random() < 0.5 else "no"
            is_trip = rng.random() < 0.5
            settle = int(rng.random() < p)  # settles at the price: null EV=0
            entry = {
                "id": rid, "action": "enter", "filled_at": "t",
                "entry_id": np.nan, "limit_price": p, "reason": np.nan,
                "side": side, "market_ask": p + 0.01, "market_bid": p - 0.01,
                "margin": 0, "settlement": settle, "contracts": 1.0,
                "capped_stake_usd": np.nan, "event_slug": f"g{gi}",
                "estimates_version": "vX", "strategy": "total",
                "period": "Q1", "minutes_left": 20.0, "edge_net": 0.05,
            }
            rows.append(entry)
            if is_trip:
                # exit at entry ± inject in the position's direction:
                # capture == inject exactly, zero under the null
                xp = p + inject if side == "yes" else p - inject
                rows.append({**entry, "id": rid + 100000, "action": "exit",
                             "entry_id": rid, "limit_price": xp,
                             "settlement": np.nan, "reason": "profit_target"})
    return pd.DataFrame(rows)


def selftest() -> int:
    rng = np.random.default_rng(20260901)
    null = build_ledger(_synthetic_tape(rng, inject=0.0))
    by_game = {k: list(v) for k, v in null.groupby("event_slug").ret}
    cm = clustered_mean(by_game)
    ok_null = cm is not None and cm.lo < 0 < cm.hi and abs(cm.mean) < 0.02
    print(f"null:     mean {cm.mean:+.4f} [{cm.lo:+.4f}, {cm.hi:+.4f}] "
          f"-> {'OK (reads ~zero)' if ok_null else 'FAIL'}")

    inj = build_ledger(_synthetic_tape(rng, inject=0.03))
    trips = inj[inj.leg == "trip"]
    by_game = {k: list(v) for k, v in trips.groupby("event_slug").ret}
    cm = clustered_mean(by_game)
    # +3¢ capture on cost E[~0.5] -> per-$ well above zero, CI excluding 0
    ok_inj = cm is not None and cm.lo > 0.02
    print(f"injected: trip mean {cm.mean:+.4f} [{cm.lo:+.4f}, {cm.hi:+.4f}] "
          f"-> {'OK (recovers +3¢ capture)' if ok_inj else 'FAIL'}")
    return 0 if (ok_null and ok_inj) else 1


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--tape", type=Path, default=DEFAULT_TAPE)
    ap.add_argument("--ledger", type=Path, default=DEFAULT_LEDGER,
                    help="Quant A's round-trip ledger (the substrate; the "
                         "tape reconstruction is the fallback and the "
                         "cross-check)")
    ap.add_argument("--selftest", action="store_true",
                    help="mutation test: synthetic null reads ~zero, "
                         "injected effect is recovered")
    args = ap.parse_args()

    if args.selftest:
        return selftest()

    mine = build_ledger(pd.read_csv(args.tape))
    if args.ledger.exists():
        m = ledger_from_a(args.ledger)
        reconcile(mine, m)
        src = args.ledger.name
    else:
        print("<!-- A's ledger absent; falling back to tape "
              "reconstruction -->")
        m, src = mine, args.tape.name
    run_map(m, src)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
