"""initial schema

Revision ID: 050b31be83f8
Revises: 
Create Date: 2026-07-31 16:30:34.448449
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '050b31be83f8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('market_slug', sa.String(length=200), nullable=False),
    sa.Column('market_id', sa.String(length=64), nullable=True),
    sa.Column('event_slug', sa.String(length=200), nullable=True),
    sa.Column('event_id', sa.String(length=64), nullable=True),
    sa.Column('game_id', sa.String(length=64), nullable=True),
    sa.Column('sports_market_type', sa.String(length=64), nullable=True),
    sa.Column('line', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('best_bid', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('best_ask', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('min_tick_size', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('min_trade_qty', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('fee_coefficient', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('game_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_live', sa.Boolean(), nullable=False),
    sa.Column('event_score', sa.String(length=32), nullable=True),
    sa.Column('event_period', sa.String(length=32), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_slug', 'captured_at', name='uq_snapshot_market_time')
    )
    op.create_index('ix_market_snapshots_captured_at', 'market_snapshots', ['captured_at'], unique=False)
    op.create_index('ix_market_snapshots_event_slug', 'market_snapshots', ['event_slug'], unique=False)
    op.create_index('ix_market_snapshots_game_id', 'market_snapshots', ['game_id'], unique=False)
    op.create_index('ix_market_snapshots_market_slug', 'market_snapshots', ['market_slug'], unique=False)
    op.create_index('ix_market_snapshots_slug_time', 'market_snapshots', ['market_slug', 'captured_at'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('predicted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('market_slug', sa.String(length=200), nullable=False),
    sa.Column('event_slug', sa.String(length=200), nullable=True),
    sa.Column('game_id', sa.String(length=64), nullable=True),
    sa.Column('sports_market_type', sa.String(length=64), nullable=True),
    sa.Column('line', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('model_probability', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('model_fair_value', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('market_bid', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('market_ask', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('market_mid', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('edge', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('config_hash', sa.String(length=64), nullable=True),
    sa.Column('is_actionable', sa.Boolean(), nullable=False),
    sa.Column('reduced_confidence', sa.Boolean(), nullable=False),
    sa.Column('confidence_notes', sa.Text(), nullable=True),
    sa.Column('resolved_outcome', sa.SmallInteger(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('was_correct', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_predictions_config_hash', 'predictions', ['config_hash'], unique=False)
    op.create_index('ix_predictions_game_id', 'predictions', ['game_id'], unique=False)
    op.create_index('ix_predictions_market_slug', 'predictions', ['market_slug'], unique=False)
    op.create_index('ix_predictions_model_version', 'predictions', ['model_version'], unique=False)
    op.create_index('ix_predictions_predicted_at', 'predictions', ['predicted_at'], unique=False)
    op.create_index('ix_predictions_version_config', 'predictions', ['model_version', 'config_hash'], unique=False)
    op.create_table('resolved_outcomes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('market_slug', sa.String(length=200), nullable=False),
    sa.Column('event_slug', sa.String(length=200), nullable=True),
    sa.Column('game_id', sa.String(length=64), nullable=True),
    sa.Column('settlement', sa.SmallInteger(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('final_score_home', sa.Integer(), nullable=True),
    sa.Column('final_score_away', sa.Integer(), nullable=True),
    sa.Column('actual_total', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_slug')
    )
    op.create_index('ix_resolved_outcomes_event_slug', 'resolved_outcomes', ['event_slug'], unique=False)
    op.create_index('ix_resolved_outcomes_game_id', 'resolved_outcomes', ['game_id'], unique=False)
    op.create_table('sportsbook_odds',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('espn_game_id', sa.String(length=32), nullable=False),
    sa.Column('game_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_name', sa.String(length=64), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('spread', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('over_under', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('over_odds', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('under_odds', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('home_moneyline', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('away_moneyline', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('open_total', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('close_total', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('is_closing_line', sa.Boolean(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('espn_game_id', 'provider_name', 'captured_at', name='uq_odds_game_provider_time')
    )
    op.create_index('ix_sportsbook_odds_espn_game_id', 'sportsbook_odds', ['espn_game_id'], unique=False)
    op.create_index('ix_sportsbook_odds_game_date', 'sportsbook_odds', ['game_date'], unique=False)
    op.create_index('ix_sportsbook_odds_is_closing_line', 'sportsbook_odds', ['is_closing_line'], unique=False)
    op.create_table('team_game_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('game_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('espn_game_id', sa.String(length=32), nullable=False),
    sa.Column('team_id', sa.String(length=32), nullable=False),
    sa.Column('team_abbrev', sa.String(length=16), nullable=True),
    sa.Column('opponent_id', sa.String(length=32), nullable=True),
    sa.Column('opponent_abbrev', sa.String(length=16), nullable=True),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('points_scored', sa.Integer(), nullable=True),
    sa.Column('points_allowed', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('season_type', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('espn_game_id', 'team_id', name='uq_team_game')
    )
    op.create_index('ix_team_game_logs_game_date', 'team_game_logs', ['game_date'], unique=False)
    op.create_index('ix_team_game_logs_season', 'team_game_logs', ['season'], unique=False)
    op.create_index('ix_team_game_logs_season_type', 'team_game_logs', ['season_type'], unique=False)
    op.create_index('ix_team_game_logs_team_date', 'team_game_logs', ['team_id', 'game_date'], unique=False)
    op.create_index('ix_team_game_logs_team_id', 'team_game_logs', ['team_id'], unique=False)
    op.create_table('book_levels',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.BigInteger(), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('level_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['market_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'side', 'level_index', name='uq_book_level')
    )
    op.create_index('ix_book_levels_snapshot_id', 'book_levels', ['snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_book_levels_snapshot_id', table_name='book_levels')
    op.drop_table('book_levels')
    op.drop_index('ix_team_game_logs_team_id', table_name='team_game_logs')
    op.drop_index('ix_team_game_logs_team_date', table_name='team_game_logs')
    op.drop_index('ix_team_game_logs_season_type', table_name='team_game_logs')
    op.drop_index('ix_team_game_logs_season', table_name='team_game_logs')
    op.drop_index('ix_team_game_logs_game_date', table_name='team_game_logs')
    op.drop_table('team_game_logs')
    op.drop_index('ix_sportsbook_odds_is_closing_line', table_name='sportsbook_odds')
    op.drop_index('ix_sportsbook_odds_game_date', table_name='sportsbook_odds')
    op.drop_index('ix_sportsbook_odds_espn_game_id', table_name='sportsbook_odds')
    op.drop_table('sportsbook_odds')
    op.drop_index('ix_resolved_outcomes_game_id', table_name='resolved_outcomes')
    op.drop_index('ix_resolved_outcomes_event_slug', table_name='resolved_outcomes')
    op.drop_table('resolved_outcomes')
    op.drop_index('ix_predictions_version_config', table_name='predictions')
    op.drop_index('ix_predictions_predicted_at', table_name='predictions')
    op.drop_index('ix_predictions_model_version', table_name='predictions')
    op.drop_index('ix_predictions_market_slug', table_name='predictions')
    op.drop_index('ix_predictions_game_id', table_name='predictions')
    op.drop_index('ix_predictions_config_hash', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index('ix_market_snapshots_slug_time', table_name='market_snapshots')
    op.drop_index('ix_market_snapshots_market_slug', table_name='market_snapshots')
    op.drop_index('ix_market_snapshots_game_id', table_name='market_snapshots')
    op.drop_index('ix_market_snapshots_event_slug', table_name='market_snapshots')
    op.drop_index('ix_market_snapshots_captured_at', table_name='market_snapshots')
    op.drop_table('market_snapshots')
    # ### end Alembic commands ###
