"""add boxscore stats to team_game_logs

Revision ID: 103f59cba43b
Revises: c34b39059f6b
Create Date: 2026-07-31 23:11:22.199235
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '103f59cba43b'
down_revision: Union[str, None] = 'c34b39059f6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_game_logs', sa.Column('fga', sa.Integer(), nullable=True))
    op.add_column('team_game_logs', sa.Column('fta', sa.Integer(), nullable=True))
    op.add_column('team_game_logs', sa.Column('oreb', sa.Integer(), nullable=True))
    op.add_column('team_game_logs', sa.Column('turnovers', sa.Integer(), nullable=True))
    op.add_column('team_game_logs', sa.Column('q1', sa.Integer(), nullable=True))
    op.add_column('team_game_logs', sa.Column('q2', sa.Integer(), nullable=True))
    op.add_column('team_game_logs', sa.Column('q3', sa.Integer(), nullable=True))
    op.add_column('team_game_logs', sa.Column('q4', sa.Integer(), nullable=True))
    op.add_column('team_game_logs', sa.Column('ot_points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_game_logs', 'ot_points')
    op.drop_column('team_game_logs', 'q4')
    op.drop_column('team_game_logs', 'q3')
    op.drop_column('team_game_logs', 'q2')
    op.drop_column('team_game_logs', 'q1')
    op.drop_column('team_game_logs', 'turnovers')
    op.drop_column('team_game_logs', 'oreb')
    op.drop_column('team_game_logs', 'fta')
    op.drop_column('team_game_logs', 'fga')
    # ### end Alembic commands ###
