"""add model calibration cache

Revision ID: 50bde990beba
Revises: 53c811eee12b
Create Date: 2026-08-01 22:01:57.633564
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '50bde990beba'
down_revision: Union[str, None] = '53c811eee12b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_calibration',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('n_observations', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric', 'as_of', name='uq_calibration_metric_asof')
    )
    op.create_index('ix_model_calibration_metric_asof', 'model_calibration', ['metric', 'as_of'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_model_calibration_metric_asof', table_name='model_calibration')
    op.drop_table('model_calibration')
    # ### end Alembic commands ###
