"""add player game logs and injury reports

Revision ID: 53c811eee12b
Revises: 72469f0d6bd7
Create Date: 2026-08-01 13:42:30.589853
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '53c811eee12b'
down_revision: Union[str, None] = '72469f0d6bd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('injury_polls',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('n_teams', sa.Integer(), nullable=False),
    sa.Column('n_designations', sa.Integer(), nullable=False),
    sa.Column('n_changes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('captured_at')
    )
    op.create_index('ix_injury_polls_captured_at', 'injury_polls', ['captured_at'], unique=False)
    op.create_table('injury_reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('team_id', sa.String(length=32), nullable=True),
    sa.Column('team_name', sa.String(length=64), nullable=True),
    sa.Column('athlete_id', sa.String(length=32), nullable=False),
    sa.Column('athlete_name', sa.String(length=120), nullable=True),
    sa.Column('position', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('status_type', sa.String(length=48), nullable=True),
    sa.Column('detail_type', sa.String(length=64), nullable=True),
    sa.Column('return_date', sa.String(length=16), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'captured_at', name='uq_injury_athlete_time')
    )
    op.create_index('ix_injury_reports_athlete_time', 'injury_reports', ['athlete_id', 'captured_at'], unique=False)
    op.create_index('ix_injury_reports_captured_at', 'injury_reports', ['captured_at'], unique=False)
    op.create_index('ix_injury_reports_team_id', 'injury_reports', ['team_id'], unique=False)
    op.create_table('player_game_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('espn_game_id', sa.String(length=32), nullable=False),
    sa.Column('game_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('season_type', sa.SmallInteger(), nullable=False),
    sa.Column('team_id', sa.String(length=32), nullable=False),
    sa.Column('athlete_id', sa.String(length=32), nullable=False),
    sa.Column('athlete_name', sa.String(length=120), nullable=True),
    sa.Column('position', sa.String(length=16), nullable=True),
    sa.Column('starter', sa.Boolean(), nullable=False),
    sa.Column('did_not_play', sa.Boolean(), nullable=False),
    sa.Column('dnp_reason', sa.String(length=64), nullable=True),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('plus_minus', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('espn_game_id', 'athlete_id', name='uq_player_game')
    )
    op.create_index('ix_player_game_logs_athlete_date', 'player_game_logs', ['athlete_id', 'game_date'], unique=False)
    op.create_index('ix_player_game_logs_espn_game_id', 'player_game_logs', ['espn_game_id'], unique=False)
    op.create_index('ix_player_game_logs_game_date', 'player_game_logs', ['game_date'], unique=False)
    op.create_index('ix_player_game_logs_team_date', 'player_game_logs', ['team_id', 'game_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_player_game_logs_team_date', table_name='player_game_logs')
    op.drop_index('ix_player_game_logs_game_date', table_name='player_game_logs')
    op.drop_index('ix_player_game_logs_espn_game_id', table_name='player_game_logs')
    op.drop_index('ix_player_game_logs_athlete_date', table_name='player_game_logs')
    op.drop_table('player_game_logs')
    op.drop_index('ix_injury_reports_team_id', table_name='injury_reports')
    op.drop_index('ix_injury_reports_captured_at', table_name='injury_reports')
    op.drop_index('ix_injury_reports_athlete_time', table_name='injury_reports')
    op.drop_table('injury_reports')
    op.drop_index('ix_injury_polls_captured_at', table_name='injury_polls')
    op.drop_table('injury_polls')
    # ### end Alembic commands ###
