"""add shadow_orders

Revision ID: c34b39059f6b
Revises: 050b31be83f8
Create Date: 2026-07-31 19:22:53.808777
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c34b39059f6b'
down_revision: Union[str, None] = '050b31be83f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shadow_orders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('prediction_id', sa.BigInteger(), nullable=True),
    sa.Column('market_slug', sa.String(length=200), nullable=False),
    sa.Column('event_slug', sa.String(length=200), nullable=True),
    sa.Column('sports_market_type', sa.String(length=64), nullable=True),
    sa.Column('line', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('model_probability', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('market_bid', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('market_ask', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('edge_net', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('would_rest', sa.Boolean(), nullable=False),
    sa.Column('expected_fee', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('binding_constraint', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_shadow_orders_decided_at', 'shadow_orders', ['decided_at'], unique=False)
    op.create_index('ix_shadow_orders_market_slug', 'shadow_orders', ['market_slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shadow_orders_market_slug', table_name='shadow_orders')
    op.drop_index('ix_shadow_orders_decided_at', table_name='shadow_orders')
    op.drop_table('shadow_orders')
    # ### end Alembic commands ###
